// AUTO-GENERATED by scripts/sync-curriculum-skill.mjs.
// Source: curriculum-skill/stages/*.md.
// Run `bun --bun run sync:curriculum-skill` to refresh.

export const FRAME_STAGE = `# Stage: Frame

Understand the audience and training context before building the session.

## Inputs

- \`session.yaml\` for audience, format, constraints
- Trainer's knowledge of the group: who they are, what they've experienced, what they already know

## Purpose

The frame stage produces a brief that every downstream stage reads. It answers: who is in the room, what do they already understand about power and nonviolent action, what constraints shape delivery, and what should they walk away able to do?

## Process (ask one at a time, conversational)

### 1. Audience profile

Ask: "Tell me about the group. Who are they, where are they from, and what's their relationship to the struggle?"

Capture:
- **Region & context**: specific country/region, current political situation, movement phase
- **Composition**: activists, organizers, community leaders, students, mixed
- **Experience with NVA concepts**: first exposure, some training, experienced practitioners
- **Group size**: affects exercise format (pairs, small groups, plenary)

### 2. Constraints & safety

Ask: "Any constraints I should know — time, language, literacy, safety?"

Capture:
- **Session length**: confirms/adjusts \`session.yaml\` value
- **Language**: primary language, interpretation needs, which terms to use in local language vs. English
- **Literacy**: affects whether slides are text-heavy or visual-heavy
- **Safety**: can materials name the local regime? Should examples avoid the trainees' own country? Are printed handouts a risk?
- **Prior sessions**: has this group covered Sharp's power theory? Spectrum of Allies? If yes, the story stage can skip foundations.

### 3. Learning objectives

Ask: "After this session, what should participants be able to do?"

Default objectives (from FUB slide 32), adjust based on trainer input:
1. **Identify** pillars of support for a specific regime or authority with enough precision to be actionable
2. **Distinguish** between broad categories and specific, targetable institutions (the four "NOT" anti-patterns)
3. **Assess** each pillar on Helvey's dimensions: importance, loyalty, vulnerability
4. **Decide** where to begin — which pillar to target first, and why, based on strategic reasoning
5. **Articulate** what each pillar supplies to the regime (obedience, resources, skills, enforcement, legitimacy)

The trainer may add, remove, or reframe these. Record the final set.

### 4. Localization needs

Ask: "Should we anchor the teaching in a case study from a specific region, or use a general/fictional example?"

Options:
- **Region-matched case**: use a case study from the trainees' region or a neighboring context (strongest resonance, but may raise safety concerns)
- **Analogous case**: use a case from a different region with structural parallels (safer, still relevant)
- **Fictional scenario**: use a plausible but invented regime context (safest, but less emotionally resonant)
- **Bolivia (FUB default)**: use the FUB's own Bolivian case study as-is

This choice feeds directly into the \`cases\` stage.

## Output

Write \`frame.md\`:

\`\`\`markdown
# Frame: [Session Title]

## Audience
- **Region & context:** [...]
- **Composition:** [...]
- **NVA experience:** [novice/intermediate/experienced]
- **Group size:** [...]
- **Prior sessions:** [what they've already covered]

## Constraints
- **Time:** [X minutes]
- **Language:** [primary + notes]
- **Literacy:** [text-heavy OK / visual-primary needed]
- **Safety:** [what to avoid in materials]

## Learning Objectives
1. [...]
2. [...]
3. [...]

## Case Study Approach
- **Type:** [region-matched / analogous / fictional / Bolivia default]
- **Notes:** [trainer's reasoning or preferences]

## Trainer Notes
[Anything else the trainer flagged — group dynamics, sensitive topics, specific requests]
\`\`\`

## Edit mode

When \`frame.md\` already exists and the trainer wants to refine:
- Read the existing frame
- Ask: "What changed? The audience? The constraints? The objectives?"
- Revise only the parts the trainer flags
- Show a summary of what changed

## Output contract

- Write \`frame.md\` to working directory
- Update \`session.yaml\`: set \`stages.frame.done: true\`, \`stages.frame.file: frame.md\`, \`stages.frame.updated: <today>\`
- Do NOT advance to story stage — ask trainer if they want to continue or lock this

## Anti-patterns to flag

- **Generic audience:** "activists" is not specific enough. Push for region, composition, experience level.
- **Skipping safety:** If the context involves an active conflict or authoritarian regime, always ask about safety constraints even if the trainer doesn't raise them.
- **Objectives as topics:** "Cover pillars of support" is a topic, not an objective. Reframe as what participants will be able to DO after the session.
- **Overloaded session:** If the trainer wants more objectives than the time allows, flag the tradeoff and help prioritize.`

export const STORY_STAGE = `# Stage: Story

Build the pedagogical arc — the sequence of concepts that takes participants from "what is power?" to "where would you begin your campaign?"

## Inputs

- \`frame.md\` — audience, constraints, learning objectives, case study approach
- \`session.yaml\` — format, session length

## Core framework: FUB Pedagogical Arc

The FUB Discussion Guide teaches Pillars of Support through a deliberate conceptual progression. The story stage adapts this arc for the specific audience.

### The canonical FUB sequence (slides 18-32)

\`\`\`
1. Power theory (Sharp)
   "Power is not held. Power is supplied."
   ↓
2. What pillars supply
   Obedience → Resources → Skills → Enforcement → Legitimacy
   ↓
3. The pillars model
   Concentric circles: regime center → bureaucrats → community → citizens
   ↓
4. Strategic analysis (Helvey)
   Each pillar differs in: importance, loyalty, vulnerability
   Key question: which can be won over, neutralized, divided, pressured?
   ↓
5. What pillars are NOT (the four anti-patterns)
   Not broad sectors → Not general social groups →
   Not undifferentiated institutions → Not static/uniform
   ↓
6. Case study
   Concrete example with named, specific pillars and tactical plans
   ↓
7. Exercise
   Name 5-8 pillars, rank them, decide where to begin and why
\`\`\`

## Process

### 1. Define the arrow

Before structuring anything: "After this session, what is the ONE idea participants must retain — even if they forget everything else?"

Default arrow (from FUB): **"If a pillar cannot be clearly named, it cannot be effectively targeted."**

The trainer may reframe this for their audience. Record the chosen arrow.

### 2. Assess what to keep, compress, or skip

Based on \`frame.md\`:

| Audience experience | Adjust |
|---|---|
| **Novice** | Full arc. Spend more time on blocks 1-2 (power theory + what pillars supply). Use concrete analogies. |
| **Intermediate** | Compress blocks 1-2 into a brief review. Expand blocks 4-5 (Helvey + anti-patterns). More case study time. |
| **Experienced** | Skip blocks 1-3 or handle as 5-min refresher. Focus on blocks 4-7 with deeper strategic analysis. Multiple case studies. |

If the group has already covered Sharp's power theory in a prior session, note that block 1 becomes a brief callback, not a full teaching segment.

### 3. Build the adapted arc

For each block, specify:
- **Concept**: what's being taught
- **Method**: lecture, discussion, pair work, group exercise, visual
- **Time allocation**: minutes
- **Key question**: the question that drives this segment
- **Transition**: how this block connects to the next

\`\`\`markdown
## Session Arc: [Title]

### The Arrow
[One sentence the group must retain]

### Block 1 — Power Theory [X min]
**Concept:** Power is not a thing rulers possess; it is supplied by institutions and people who can withdraw it.
**Method:** [e.g., "Open with the Sharp quote. Ask: 'Where does the government in [their context] get its power?' Collect answers on a board."]
**Key question:** "What happens when a pillar withdraws its support?"
**Transition:** "So if power is supplied, who exactly is supplying it? That's what pillars are."

### Block 2 — What Pillars Supply [X min]
**Concept:** Pillars provide five things: obedience, resources, skills, enforcement, legitimacy.
**Method:** [adapted for audience]
**Key question:** "Which of these five does [local institution X] supply?"
**Transition:** "Now that we know what pillars give, let's see who they are — and where they sit in relation to the regime."

### Block 3 — The Pillars Model [X min]
**Concept:** Concentric circles from regime center (mayor, council) through bureaucrats to community leaders and citizens at the periphery.
**Method:** [adapted]
**Key question:** "In your context, who is closest to the center? Who is at the periphery?"
**Transition:** "Not all pillars are equal. Some matter more. Some are more reachable. How do we tell the difference?"

### Block 4 — Strategic Analysis (Helvey) [X min]
**Concept:** Assess each pillar on importance (to the regime), loyalty (how committed), vulnerability (how reachable). Strategy = shifting pillar behavior over time.
**Method:** [adapted — this is where group discussion deepens]
**Key question:** "Which pillars are essential to the regime but have wavering loyalty?"
**Transition:** "Before we practice this, let's clear up the most common mistakes people make when identifying pillars."

### Block 5 — What Pillars Are NOT [X min]
**Concept:** The four anti-patterns:
  1. Not broad sectors ("the economy") — identify specific chambers, companies, actors
  2. Not general social groups ("religion", "youth") — identify specific organizations, structures
  3. Not undifferentiated institutions ("the military") — break into units, commands, divisions
  4. Not static or uniform — assess loyalty, cohesion, dependence, susceptibility for each
**Method:** [adapted — examples should use local/relevant institutions]
**Key question:** "Can you name it specifically enough to target it?"
**Transition:** "Let's see what this looks like in practice."

### Block 6 — Case Study [X min]
**Concept:** Apply the framework to a real (or fictional) context with named, specific pillars.
**Method:** [determined by cases stage — trainer presents, then group discusses]
**Key question:** "Which of these pillars would you target first, and why?"
**Transition:** "Now it's your turn."

### Block 7 — Exercise [X min]
**Concept:** Participants apply the framework to their own context (or a provided scenario).
**Instructions:** (from FUB slide 32)
  1. Name 5-8 pillars of support
  2. Rank them: most important, most vulnerable, most realistic to influence
  3. Decide where you would begin and why
**Closing question:** "Where can you create the greatest strategic shift with the least waste of energy?"
\`\`\`

### 4. Add engagement beats

Every 10-15 minutes of lecture, insert an engagement beat:
- **Pair discussion**: "Turn to your neighbor and..." (30-60 seconds)
- **Group question**: trainer poses a question, collects 2-3 answers
- **Show of hands**: quick poll to gauge the room
- **Local example**: trainer inserts a reference to a local institution the group knows

Mark where these go in the arc: \`[ENGAGEMENT: ...]\`

### 5. Time check

Sum the block times. Compare to \`session.yaml.session_length_minutes\`. If over:
- Flag which blocks to compress
- Suggest what to cut (usually block 3 for experienced groups, or block 5 can be woven into the case study instead of taught standalone)
- Never cut the exercise for full-session format — it's the whole point

## Format overlays

- **full-session (90-120 min):** Full arc as above. Exercise gets 20-30 min.
- **workshop (45-60 min):** Compress blocks 1-3 to 10 min total. Expand exercise to 25 min. Case study becomes a brief worked example (5 min) rather than a full analysis.
- **overview (20-30 min):** Blocks 1-4 only, no exercise. End with the closing question as a provocation. Case study is one slide.

## Edit mode

When \`story.md\` already exists and the trainer wants to refine:
- Read the existing arc
- Ask: "What needs adjustment? Timing? A specific block? The engagement beats?"
- Common refinements:
  - "Too theoretical" → move engagement beats earlier, add more local examples
  - "Too long" → compress or merge blocks, reduce case study time
  - "Wrong emphasis" → rebalance time between blocks
  - "Needs more discussion" → convert lecture blocks to facilitated discussion
- Show what changed

## Output contract

- Write \`story.md\` to working directory
- Update \`session.yaml\`: set \`stages.story.done: true\`, \`stages.story.file: story.md\`, \`stages.story.updated: <today>\`

## Anti-patterns to flag

- **Lecture-only arc:** If no engagement beats appear in 15+ minutes, flag it. Participants learn by doing, not listening.
- **Exercise squeezed out:** If time pressure cuts the exercise, push back — for full-session format, the exercise IS the learning.
- **Concept without question:** Every block needs a driving question. If the trainer can't articulate one, the block isn't focused.
- **Anti-patterns taught in isolation:** Block 5 is most powerful when woven into the case study — "look, Bolivia didn't say 'the economy', they said 'CAINCO in Santa Cruz.'" Consider merging.
- **Skipping the arrow:** Without a single-sentence takeaway, the session sprawls. Insist on defining it.`

export const CASES_STAGE = `# Stage: Cases

Select, adapt, and prepare case studies that make the Pillars of Support framework concrete for the audience.

## Inputs

- \`frame.md\` — audience region/context, case study approach preference, safety constraints
- \`story.md\` — where the case study sits in the arc, how much time it gets
- \`session.yaml\` — format

## Why this stage matters

The case study is where theory becomes real. A well-chosen case does three things:
1. Shows what properly identified pillars look like (specific, named, differentiated)
2. Demonstrates strategic reasoning (why target this pillar first?)
3. Gives participants a mental model to apply in the exercise

A poorly chosen case — too distant, too abstract, or too close to home — undermines all three.

## Source material

### Primary: FUB Bolivian Case Study (slide 26)

The FUB's own reference case. 13 named pillars:
1. Embassies (Ministry of Foreign Affairs)
2. International allies (NGOs)
3. Indigenous groups of highlands (Aymara)
4. Local power structures (municipalities)
5. CAINCO in Santa Cruz (economic engine, business group)
6. Media (state and "independent")
7. Police
8. Plurinational Electoral Body
9. Social movements (unions, federations)
10. Military
11. False political opposition
12. Judicial branch
13. Drug trafficking networks

This case includes a tactical planning matrix (slide 27) showing pillar-by-pillar goals, methods, and tactics across September-October timeline.

### Supporting: SNVA corpus

The broader corpus contains additional case studies and conceptual grounding:
- ICNC Pillars of Support Concept Guide
- SNVA Case Studies by Region
- Helvey's On Strategic Nonviolent Conflict
- Sharp's works (From Dictatorship to Democracy, Role of Power, 198 Methods)
- Chenoweth & Stephan (Why Civil Resistance Works)

## Process

### 1. Match case to audience

Based on \`frame.md\`'s case study approach:

| Approach | How to select |
|---|---|
| **Region-matched** | Find a case from the same country or region. Check corpus for coverage. If the corpus has relevant material, use it with citation. If not, work with the trainer to identify a case they know — flag that it won't have corpus backing. |
| **Analogous** | Find a case from a different region with structural parallels. Good matches share: similar regime type, comparable pillar structure, relevant strategic lessons. E.g., Serbia (Otpor) for movements against electoral fraud; Philippines (People Power) for military defection dynamics. |
| **Fictional** | Build a plausible scenario with the trainer. Must have enough specificity to demonstrate the framework — named institutions, differentiated pillars, clear power dynamics. Avoid making it obviously "about" the trainees' own context. |
| **Bolivia (default)** | Use the FUB case as-is. Strongest option when the audience has no regional sensitivity concerns and the trainer is comfortable with Latin American context. |

### 2. Build the case brief

For the selected case, produce:

\`\`\`markdown
## Case Study: [Name]

### Context (2-3 sentences)
[Country, period, what was happening, who was in power]

### Pillars Identified (5-8 minimum, named specifically)
| # | Pillar | Category | What it supplies | Notes |
|---|--------|----------|-----------------|-------|
| 1 | [Specific name] | [institutional/informal/economic/social/security/...] | [obedience/resources/skills/enforcement/legitimacy] | [key detail] |
| ... | ... | ... | ... | ... |

### Strategic Analysis
- **Most important to regime:** [which pillars and why]
- **Most vulnerable:** [which pillars showed cracks and why]
- **Where the movement began:** [which pillar they targeted first and the reasoning]

### What makes this case instructive
- [How it demonstrates specificity — named institutions, not categories]
- [How it shows Helvey dimensions in action]
- [What the movement got right or wrong in pillar targeting]

### Discussion prompts for trainer
1. [Question that connects this case to the audience's context]
2. [Question about a strategic choice the movement made]
3. [Question that surfaces a "What Pillars Are NOT" anti-pattern]
\`\`\`

### 3. Prepare anti-pattern examples from the case

For each of the four "What Pillars Are NOT" categories, prepare a contrast pair from the case:

- **Not broad sectors:** "The Bolivian movement didn't say 'the economy' — they identified CAINCO in Santa Cruz specifically, because CAINCO controlled the economic engine of the eastern lowlands."
- **Not general social groups:** "They didn't say 'indigenous groups' — they identified the highland Aymara specifically, who had distinct interests from lowland indigenous communities."
- **Not undifferentiated institutions:** "They didn't say 'the military' — they tracked specific units and chains of command, because different commanders responded differently to pressure."
- **Not static:** "The police and military shifted loyalty at different moments. The tactical plan shows different goals for the same pillar across September vs. October."

### 4. Prepare the tactical dimension (if time allows)

For full-session format, the case study can include the tactical planning matrix:
- Which pillar was targeted in which month
- What methods were used (persuasion, disobedience, name+shame, laughtivism)
- What tactics matched each method (artistic protests, sit-ins, social media campaigns, graffiti)
- What recruitment and movement-building happened alongside

This is from FUB slide 27 (the September-October matrix). Adapt the format for the selected case.

### 5. Trainer delivery notes

Add brief notes on how to present the case:
- Which details to emphasize for this audience
- Which discussion prompts to use (from the list above)
- How long to spend (from \`story.md\` time allocation)
- Whether to present the full case first then discuss, or build it interactively with the group

## Edit mode

When \`cases.md\` already exists and the trainer wants to refine:
- Ask: "What needs adjustment? Different case? More detail? Different emphasis?"
- Common refinements:
  - "Too distant" → find a closer regional match or add bridging context
  - "Too sensitive" → switch to analogous or fictional case
  - "Not enough detail" → expand the pillar list or add tactical dimension
  - "Need a second case" → add a contrasting case for experienced groups

## Output contract

- Write \`cases.md\` to working directory
- Update \`session.yaml\`: set \`stages.cases.done: true\`, \`stages.cases.file: cases.md\`, \`stages.cases.updated: <today>\`

## Anti-patterns to flag

- **Case without specificity:** If the case study itself uses broad categories ("the business sector"), it undermines the lesson. Every pillar in the case must be named specifically enough to target.
- **Case too close to home:** If the case uses the trainees' own current struggle, it can trigger emotional responses that derail analysis. Check with the trainer. Some groups can handle it; many can't.
- **Fabricated history:** Never invent historical events or attribute actions to real movements that didn't happen. If using a fictional case, label it clearly as fictional. If citing the corpus, quote accurately.
- **All theory, no people:** Good case studies include human detail — the police wives holding signs ("Esposas de Policias"), the eggs with "Si" written on them, the specific neighborhood where graffiti campaigns ran. These details make the case memorable.
- **Single dimension:** Don't just list pillars — show how they were analyzed and targeted. The tactical matrix is what makes the Bolivian case powerful, not just the pillar list.`

export const DESIGN_STAGE = `# Stage: Design

Structure each slide for a training context — concept clarity, discussion flow, and facilitator support.

## Inputs

- \`story.md\` — the pedagogical arc with blocks and timing
- \`cases.md\` — case study content and discussion prompts
- \`session.yaml\` — format, audience

## Core principle

**Training slides serve the facilitator, not the screen.** Slides anchor discussion, not replace it. Every slide should work as a visual anchor while the trainer talks, not as a document to be read.

## Process

### 1. Map story blocks to slide types

Read \`story.md\`. For each block, assign slides using training-specific types:

| Content | Slide type |
|---------|-----------|
| Session title + agenda | Title slide |
| New concept introduction | Concept slide (term + definition + visual) |
| Key quote (Sharp, Helvey) | Quote slide |
| Framework/model | Diagram slide (pillars model, concentric circles) |
| Anti-pattern teaching | Contrast slide (wrong vs. right) |
| Case study overview | Context slide (country, period, situation) |
| Pillar list from case | Table/list slide |
| Tactical matrix | Grid slide |
| Discussion prompt | Discussion slide (question + visual anchor) |
| Exercise instructions | Exercise slide (numbered steps) |
| Transition between blocks | Section break |
| Session closing | Closing slide (the arrow + closing question) |

### 2. Training-specific design rules

Unlike product decks, training slides follow different rules:

**Text density:**
- Concept slides: term + 1-2 sentence definition. The trainer elaborates verbally.
- Quote slides: the quote only. No commentary on the slide.
- Discussion slides: the question only, large font. No suggested answers.
- Exercise slides: numbered steps, clear and complete — participants need to read these without the trainer repeating them.

**Visual elements:**
- Diagrams over bullet points. The pillars-as-columns model (FUB slide 18), the concentric circles (FUB slide 20), and the contrast pairs (slides 22-25) are the visual vocabulary.
- Case study photos when available — the Bolivian protest photos (eggs with "Si", police wives) make the case visceral.
- Color-coding for the five things pillars supply: assign a consistent color to obedience, resources, skills, enforcement, legitimacy.

**Progressive disclosure:**
- For the "What Pillars Are NOT" section: reveal one anti-pattern at a time
- For the Helvey dimensions: introduce importance first, then loyalty, then vulnerability
- For the case study: show context first, then pillar list, then tactical matrix

### 3. Slide-by-slide specs

For each slide, write:

\`\`\`markdown
## Slide N: [Visual headline or concept name]

**Type:** [from slide type table]
**Block:** [which story block this belongs to]
**Priority:** essential | standard | expandable
**Visual:** [what the audience sees — diagram, quote, photo, table]
**Facilitator notes:** [what the trainer says/does with this slide — NOT a script, but cues and key points]
**Engagement:** [if applicable — question to ask, show of hands, pair discussion]
**Transition:** [cue to move to next slide]
**Time:** [estimated seconds/minutes on this slide]
\`\`\`

### 4. Key slides for the Pillars module

These slides should appear in every format:

**The Sharp quote (Block 1):**
- Visual: the palace-on-pillars diagram with scissors cutting the base
- Quote: "Pillars of support are institutions and sections of the society that supply the existing regime with sources of power..." — Sharp
- Facilitator cue: "Before I show this quote, I want to ask you..."

**The five supplies (Block 2):**
- Visual: five labeled boxes or icons — Obedience, Resources, Skills, Enforcement, Legitimacy
- Facilitator cue: "For each of these, can someone give me an example from [audience's context]?"

**Concentric circles (Block 3):**
- Visual: the concentric circle diagram with regime at center, citizens at periphery
- Right side: labels for each ring (Mayor, City Council, Local Bureaucrats, Community Leaders, Business Leaders, Citizens)
- Facilitator cue: "Who is closest to the center in your context?"

**Helvey dimensions (Block 4):**
- Visual: two-column layout — left: what pillars ARE (active relationships, sources of capacity); right: key questions (which essential? vulnerable? can be won over/neutralized/divided/pressured?)
- Facilitator cue: "Strategy is shifting the behavior of pillars over time."

**Contrast slides (Block 5) — one per anti-pattern:**
- Visual: wrong label crossed out → right label with specific examples
- E.g., ~~"the economy"~~ → "CAINCO in Santa Cruz" + "specific business chambers" + "key companies"
- Facilitator cue: "Why does this distinction matter for strategy?"

**Exercise slide (Block 7):**
- Visual: three numbered steps, large and clear
  1. Name 5-8 pillars of support
  2. Rank them: most important, most vulnerable, most realistic to influence
  3. Decide where you would begin and why
- Closing question in bold: "Where can you create the greatest strategic shift with the least waste of energy?"

### 5. Mark essential vs. expandable

For time flexibility:
- **Essential:** Title, Sharp quote, five supplies, one contrast example, exercise instructions, closing
- **Standard:** Concentric circles, Helvey dimensions, all four contrast slides, case study overview
- **Expandable:** Tactical matrix, additional case study detail, extended discussion slides

### 6. Plan the exercise format

Based on group size from \`frame.md\`:
- **< 10 people:** Individual work → plenary discussion
- **10-25 people:** Pairs or triads → share with full group
- **25+ people:** Small groups (4-5) → each group presents one pillar analysis → plenary synthesis

Specify on the exercise slide(s) how the trainer should organize the work.

## Output structure

\`\`\`
slides/
  01-title.md
  02-section-power-theory.md
  03-sharp-quote.md
  04-five-supplies.md
  ...
  NN-exercise.md
  NN-closing.md
  outline.md          (summary table)
\`\`\`

\`outline.md\` contains:
\`\`\`markdown
| # | Slide | Type | Block | Priority | Time |
|---|-------|------|-------|----------|------|
| 1 | [title] | Title | - | essential | 30s |
| 2 | Power Theory | Section Break | 1 | essential | 10s |
| ... | ... | ... | ... | ... | ... |
| Total | | | | | Xm |
\`\`\`

## Edit mode

When \`slides/\` already exists:
- Ask: "Which slide needs work? Or is it the overall flow?"
- Can edit a single slide spec without touching others
- Can reorder by renumbering files
- Can add/remove discussion slides based on time adjustments

## Output contract

- Create \`slides/\` directory with individual slide specs + \`outline.md\`
- Update \`session.yaml\`: set \`stages.design.done: true\`, \`stages.design.file: slides/\`, \`stages.design.updated: <today>\`

## Anti-patterns

| Anti-pattern | Symptom | Fix |
|---|---|---|
| **Wall of text** | Slide contains full explanation | Move explanation to facilitator notes; slide shows concept + visual only |
| **Missing facilitator cues** | No notes on what to say or do | Every slide needs at least a one-line facilitator cue |
| **Decoration over function** | Pretty but doesn't teach | Every visual element must serve comprehension or engagement |
| **Exercise without structure** | "Discuss pillars" with no steps | Clear numbered instructions + time + group format |
| **No discussion slides** | All lecture, no interaction points | Insert discussion slides between concept blocks |`

export const CURRICULUM_SKILL_STAGES = [
  { stage: 'frame', body: FRAME_STAGE },
  { stage: 'story', body: STORY_STAGE },
  { stage: 'cases', body: CASES_STAGE },
  { stage: 'design', body: DESIGN_STAGE },
] as const

export const CURRICULUM_SKILL_PROMPT = CURRICULUM_SKILL_STAGES.map(
  ({ stage, body }) => `<curriculum_skill_stage name="${stage}">\n${body}\n</curriculum_skill_stage>`,
).join('\n\n')
